runtime: python311

# Basic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  PORT: 8080
  PYTHONUNBUFFERED: 1
  LOG_LEVEL: INFO
  GOOGLE_GENAI_USE_VERTEXAI: 1
  GOOGLE_CLOUD_LOCATION: us-central1
  DATABASE_URL: sqlite:///./agentic_ai.db
  MCP_SERVER_URL: http://localhost:8000
  MAX_DAILY_AI_REQUESTS: 50
  MAX_HOURLY_AI_REQUESTS: 10
  AI_INSIGHTS_ON_DEMAND_ONLY: true

# Resource limits
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check
readiness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2 