steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'APP_VERSION=${_APP_VERSION}',
      '--build-arg', 'BUILD_TIMESTAMP=${_BUILD_TIMESTAMP}',
      '--build-arg', 'GIT_COMMIT=${_GIT_COMMIT}',
      '-t', '${_IMAGE_NAME}:${_APP_VERSION}',
      '-t', '${_IMAGE_NAME}:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:${_APP_VERSION}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:latest']

# Store images in Google Container Registry
images:
  - '${_IMAGE_NAME}:${_APP_VERSION}'
  - '${_IMAGE_NAME}:latest'

# Build timeout
timeout: '1200s'

# Machine type for faster builds
options:
  machineType: 'E2_HIGHCPU_8' 